// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//cada termino en la secuencia fibonacci es generado sumando los dos numeros previos.
//calcular la suma de todos los numeros fibonacci pares entre 4000000

// function sumOfEvenFibonacci(limit) {
//     let fib = [1, 2];
//     let sum = 2; // Start with 2 because the second term is even

//     let i = 2;
//     while (fib[i - 1] + fib[i - 2] <= limit) {
//         fib[i] = fib[i - 1] + fib[i - 2];
//         if (fib[i] % 2 === 0) {
//             sum += fib[i];
//         }
//         i++;
//     }

//     return sum;
// }

// const limit = 4000000;
// const result = sumOfEvenFibonacci(limit);
// console.log(result);



function fibonacci(number) {
    let fib = [1, 2];
    let result = 2;
    const max = Number.MAX_SAFE_INTEGER;

    for (let i = 2; i < number; i++) {
        fib[i] = fib[i - 1] + fib[i - 2];
        if (fib[i] % 2 === 0) {

            if (result < max) {
                result += fib[i];
            }
        }


    }

    return console.log(result);
}

fibonacci(4000000);

